#!/usr/bin/env node
var fs = require('fs');
var path = require('path');
var colors = require('colors');
var inquirer = require('inquirer');
var scaffolt = require('scaffolt');

var assignmentsRoot = "/Users/jacobsmith/Code/theironyard/Assignments";

var questions = [
  {
    type: "input",
    name: "name",
    message: "Assignment name"
  },
  {
    type: "list",
    name: "type",
    message: "Assignment type",
    choices: ["Code", "Reading", "Video", "Design"]
  },
  {
    type: "list",
    name: "course",
    message: "Assignment course",
    choices: [ "JavaScript", "Ruby", new inquirer.Separator(), "New Course" ]
  }
];

var courses = {
  "JavaScript": "js",
  "Ruby": "ruby"
};

inquirer.prompt( questions, function( answers ) {
  assert(answers.name, "name is required");
  var course = courses[answers.course];
  assert(course, "course is required");

  var assignmentPath = path.join(assignmentsRoot, course, answers.name.replace(/ /g, '-').toLowerCase());

  scaffolt('assignment', answers.name, {
    generatorsPath: process.env._HOMEWORK_ROOT + "/share/generators",
    parentPath: assignmentPath
  }, function(error){
    assert(!error, error);
    // TODO: missing callback, amond other things
    fs.mkdir(assignmentPath + "/resources");
  });
});

function assert(condition, message) {
  if (!condition) {
    console.error(message.red);
    process.exit(1);
  }
}

