#!/usr/bin/env node
/*
# Usage: homework sync
# Summary: Creates or updates the assignment in the current directory
# Help: Creates or updates the assignment in the current directory
*/

var rootPath = process.env._HOMEWORK_ROOT;

var inquirer = require('inquirer');
var exec = require('child_process').exec;
var util = require('util');

var ui = new inquirer.ui.BottomBar("Working");
var assignmentsPath = "/Users/jacobsmith/Code/theironyard/Assignments/js/surf-and-paddle";
var cmd = util.format("tar czf %s.tar.gz %s", assignmentsPath, assignmentsPath);

exec(cmd , function(error, stdout, stderr) {
  process.exit();
});
