#!/usr/bin/env node
/*
# Usage: homework debug
# Summary: Outputs useful debug information.
# Help: Outputs useful debug information.
*/

var config = require(process.env._HOMEWORK_ROOT + "/package.json");

console.log("Homework CLI Version: %s", config.version);
console.log("OS/Architecture: %s/%s", process.platform , process.arch);
console.log("Home Directory: %s", process.env.HOME);
console.log("Config File: %s", "<not configured>");
console.log("API Key: %s", "<not configured>");
console.log("API URL: %s", "<not configured>");
console.log("Homework Directory: %s", "<not configured>");
console.log("If you are having trouble and need to file an issue (%s) please include this information (except your API key. Keep that private).", config.bugs.url);
