#!/usr/bin/env node
/*
# Usage: homework plan
# Summary: Plan the assignments for your current class
# Help: Plan the assignments for your current class
*/

var colors = require('colors');
var moment = require('moment');
var inquirer = require('inquirer');

console.log('Current Class: '.bold + 'Front End Engineering, Greenville Jan 2015');

inquirer.prompt([{
  type: "checkbox",
  name: "assignments",
  message: "Selected Assignments",
  choices: [
    {name: "Hello World", value: "Hello World", checked: true},
    {name: "Surf and Paddle", value: "Surf and Paddle"}
  ]
}], function(answers){

});
