#!/usr/bin/env node
/*
# Usage: homework --version
# Summary: Display the version of the homework program
# Help: Display the version of the homework program
*/

var ROOT = process.env._HOMEWORK_ROOT;
var packageJson = require(ROOT + "/package.json");
var format = require('util').format;

console.log(format("homework %s", packageJson.version));
